### PR TITLE
tmux sessionaizer: make it more reliable (the revenge)

### PR DESCRIPTION
**Pull request by saccarosium**
Now it should work now

### CODE REVIEW

**Comment by saccarosium** [comment]
@ThePrimeagen I solved the problem you had.

**Comment by ThePrimeagen** [comment]
wait

i'll look at this :)

sorry, i have just been so swamped since may this year.  but i need to update my experiences here soon :)

**Comment by jjant** [comment]
bump

**Comment by saccarosium** [comment]
@ThePrimeagen friendly ping

**Comment by saccarosium** [comment]
Shameless plug: I've made an improved version of the script called [tmux-companion](https://github.com/saccarosium/tmux-companion).

**Pull request closed without merging**
